### ISSUE TITLE
No Data since 2min start login

### ISSUE THREAD

**Issue by TodiDives** [TA2k/ioBroker.gruenbeck#29]
gruenbeck.0 | 2021-02-21 14:02:03.382 | error | (4235) Error: Request failed with status code 429
gruenbeck.0 | 2021-02-21 14:02:01.882 | error | (4235) No Data since 2min start login

Ich bekomme einfach keine Daten mehr geliefert.
In der Grünbeck App habe ich die Daten, der LogIn ist richtig.

**Comment by rywr** [comment]
Seit gestern liefert der Adapter keine Daten.
Abruf war alle 10min eingestellt.
Restart alle 2h.
Nach dem Restart kommt ein http-Fehler 429 (too many connects)
Zu dem Zeitpunkt erhält die Grünbeck-App auch keine Daten mehr.

Nach dem Stopp des Adapters kommt irgendwann ein Connect der App. Der Adapter erhält dann auch wieder Daten.
Die Wartezeit kann ich nicht genau angeben.
Danach kommen für 3 bis 4h Daten, bis der Abruf erneut abbricht.

Ein Vergrößern des Abrufintervalls auf 15min brachte keine Besserung. Es hilft nur, den Abruf für eine gweisse Zeit zu stoppen.

Es scheint so, als hätte Grünbeck den Zugriff beschränkt? Ist bekannt, welches Abrufintervall mittlerweile noch "erlaubt" ist?

**Comment by TA2k** [comment]
Probiert mal alle 30min und schaut was das Interval ist

**Comment by rywr** [comment]
Hmm, gestern abend auf 20 min gestellt - funktioniert über Nacht.
dann schrittweise wieder auf 10min-Intervall zurück - funktioniert auch. Es gab nur einen http-429-Fehler, aber der Adapter läuft weiterhin.
Es gibt kein einheitliches Verhalten, an dem man ableiten kann, ob das nun ein Server-Fehler ist oder ob tatsächlich aktiv von Grünbeck geblockt wird. 
Ich hatte vor einiger Zeit direkt bei Grünbeck nachgefragt und damals wurde ein Mindestabstand von 5min genannt. Hoffen wir mal, dass das so bleibt.

Es wäre schön, wenn Grünbeck endlich eine offizielle API einführen würde oder zumindest die aktuell gültigen Rahmenbedingungen angeben würde. Ein zusätzlicher lokaler Zugriff wäre natürlich auch schön. 
Aber dafür kannst du, TA2k, ja nichts ;-)

**Comment by rywr** [comment]
Hi, es gibt leider wieder Probleme mit Grünbeck, die ich nicht eingrenzen kann. Ich wollte keinen neuen Issue anlegen, deshalb füge ich die Infos hier als Kommentar an.
Vor ein/zwei Tagen wurden in der Grünbeck-App Wartungsarbeiten gemeldet. Danach musste eine erneute Anmeldung in der App erfolgen.
Anschließend war kein Datenabruf mehr über den Adapter möglich.
Auch längere Adapter-Deaktivierung bringt keine Änderung.
Der Abruf liefert http-Fehler 401. Kann es sein, dass Grünbeck das Auth-Verfahren erneut geändert hat?

Das Protokoll:
gruenbeck.0 | 2021-03-16 20:33:49.276 | error | (26119) Error: Request failed with status code 401
-- | -- | -- | --
gruenbeck.0 | 2021-03-16 20:33:49.275 | error | (26119) https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices//realtime/leave?api-version=2020-04-07
gruenbeck.0 | 2021-03-16 20:33:49.198 | info | (26119) Terminated (NO_ERROR): Without reason
gruenbeck.0 | 2021-03-16 20:33:49.196 | info | (26119) terminating
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | at endReadableNT (_stream_readable.js:1223:12)
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | at IncomingMessage.emit (events.js:326:22)
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:236:11)
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
gruenbeck.0 | 2021-03-16 20:33:49.142 | error | (26119) Error: Request failed with status code 401
gruenbeck.0 | 2021-03-16 20:33:49.140 | error | (26119) unhandled promise rejection: Request failed with status code 401
Unhandled | 2021-03-16 20:33:49.139 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
gruenbeck.0 | 2021-03-16 20:33:47.556 | info | (26119) starting. Version 0.0.24 in /opt/iobroker/node_modules/iobroker.gruenbeck, node: v12.19.0, js-controller: 3.1.5
host.0176ed33714b | 2021-03-16 20:33:43.464 | info | instance system.adapter.gruenbeck.0 started with pid 26119
host.0176ed33714b | 2021-03-16 20:33:42.445 | info | Restart adapter system.adapter.gruenbeck.0 because enabled
host.0176ed33714b | 2021-03-16 20:33:42.445 | info | instance system.adapter.gruenbeck.0 terminated with code 0 (NO_ERROR)
gruenbeck.0 | 2021-03-16 20:33:42.032 | error | (26104) Error: Request failed with status code 401
gruenbeck.0 | 2021-03-16 20:33:42.031 | error | (26104) https://prod-eu-gruenbeck-api.azurewebsites.net/api/devices//realtime/leave?api-version=2020-04-07

**Comment by TA2k** [comment]
gefixt

**Comment by rywr** [comment]
Danke, läuft wieder.
